export const aiModuleConfigs = {
  offline: {
    label: "线下好店",
    defaultStatuses: ["想去", "常去", "去过", "收藏"],
    categoryAliases: {
      restaurant: "饭店",
      餐厅: "饭店",
      餐馆: "饭店",
      hotel: "住宿",
      stay: "住宿",
      homestay: "住宿",
      民宿: "住宿",
      attraction: "景点",
      scenic: "景点",
      景区: "景点",
      cafe: "咖啡店",
      coffee: "咖啡店",
      teahouse: "茶馆",
      tea: "茶馆",
    },
    statusAliases: {
      wishlist: "想去",
      want: "想去",
      frequent: "常去",
      favorite: "常去",
      visited: "去过",
      done: "去过",
      saved: "收藏",
      bookmark: "收藏",
    },
  },
  shopping: {
    label: "网购好物",
    defaultStatuses: ["回购", "推荐", "在用", "收藏"],
    categoryAliases: {
      snack: "零食",
      food: "零食",
      digital: "数码",
      electronics: "数码",
      gadget: "数码",
      daily: "日用百货",
      household: "日用百货",
      home: "日用百货",
      fashion: "服饰",
      clothes: "服饰",
      clothing: "服饰",
      medicine: "药品",
      medical: "药品",
      health: "药品",
    },
    statusAliases: {
      rebuy: "回购",
      repurchase: "回购",
      recommended: "推荐",
      use: "在用",
      using: "在用",
      current: "在用",
      saved: "收藏",
      bookmark: "收藏",
    },
  },
  websites: {
    label: "网站收集",
    defaultStatuses: ["常用", "推荐", "收藏", "观察中"],
    categoryAliases: {
      tool: "文件工具",
      tools: "文件工具",
      filetool: "文件工具",
      convert: "文件工具",
      ai: "AI 工具",
      aitool: "AI 工具",
      llm: "AI 工具",
      resource: "资源网站",
      resources: "资源网站",
      directory: "资源网站",
      catalog: "资源网站",
      dev: "开发参考",
      developer: "开发参考",
      docs: "开发参考",
      reference: "开发参考",
    },
    statusAliases: {
      frequent: "常用",
      daily: "常用",
      recommended: "推荐",
      saved: "收藏",
      bookmark: "收藏",
      observing: "观察中",
      pending: "观察中",
      watch: "观察中",
    },
  },
  inbox: {
    label: "待处理",
    defaultStatuses: ["未处理", "已分析", "已整理", "已归档"],
    categoryAliases: {
      unsorted: "未归类",
      todo: "待整理",
      idea: "灵感",
      inspiration: "灵感",
      material: "素材",
      clip: "素材",
      pending: "待判断",
    },
    statusAliases: {
      new: "未处理",
      raw: "未处理",
      analyzed: "已分析",
      review: "已分析",
      organized: "已整理",
      archived: "已归档",
    },
    targetModuleAliases: {
      offline: "offline",
      shopping: "shopping",
      shop: "shopping",
      websites: "websites",
      website: "websites",
      web: "websites",
      inbox: "inbox",
      songs: "songs",
      song: "songs",
      music: "songs",
    },
  },
  songs: {
    label: "歌曲",
    defaultStatuses: ["常听", "想听", "会唱", "KTV必点", "收藏"],
    categoryAliases: {
      pop: "流行",
      popular: "流行",
      ktv: "KTV",
      karaoke: "KTV",
      nostalgia: "怀旧",
      oldies: "怀旧",
      love: "情歌",
      ballad: "情歌",
      rock: "摇滚",
      ost: "影视OST",
      soundtrack: "影视OST",
      instrumental: "纯音乐",
      ambient: "纯音乐",
    },
    statusAliases: {
      favorite: "常听",
      repeat: "常听",
      listenlater: "想听",
      later: "想听",
      sing: "会唱",
      cansing: "会唱",
      mustsing: "KTV必点",
      ktvmust: "KTV必点",
      saved: "收藏",
      bookmark: "收藏",
    },
  },
};

export function getModuleAiConfig(moduleId) {
  const config = aiModuleConfigs[moduleId];

  if (!config) {
    throw new Error("不支持的模块类型。");
  }

  return config;
}
